var na = "Amit Mishra";
console.log("name : ".concat(na));
na = 10;
console.log("name : ".concat(na));
var arr = ['aakash', 'shivam'];
console.log(arr);
arr.push(100);
console.log(arr);
var arr2 = ['aakash', 'shivam'];
console.log(arr2);
arr2.push("faizan");
console.log(arr2);
var xy = ['cse', 'csbs', 'ds'];
xy.push(100);
console.log(xy);
